### ISSUE TITLE
Drafts de PRs ou issues?

### ISSUE THREAD

**Issue by DyeffersonAz** [mizerablebr/anki-manual#14]
Descobri ultimamente essa [nova funcionalidade](https://github.blog/2019-02-14-introducing-draft-pull-requests/) (talvez nem tão nova assim 😝, é de 2019) do Github que te deixa iniciar um rascunho de um pull request, ou seja, pode indicar que a tradução está sendo feita com indicações reais de início no trabalho.
Criei essa issue para pedir a opinião de vocês. O que acham desse recurso e será que ele pode substituir as issues? Aberto a opiniões, vim aqui somente pra informar.

**Comment by Cardosaum** [comment]
Olá, @DyeffersonAz !

Peço desculpas pela demora, não fui notificado dessa issue.

Na minha opinião, usar rascunho de PRs seria mais interessante pois é possível acompanhar o progresso do trabalho e ao mesmo tempo facilitaria a tradução simultânea de um mesmo arquivo.

**Comment by DyeffersonAz** [comment]
Que bom, @Cardosaum . Aguardo a opinião do @mizerablebr .

**Comment by mizerablebr** [comment]
@DyeffersonAz Acho excelente a ideia e aplicação, já podemos começar.
