### ISSUE TITLE
[pergunta] como deve ser feita contribuições/traduções ao projeto?

### ISSUE THREAD

**Issue by paulolimac** [mizerablebr/anki-manual#17]
1. Gostaria de saber como devem ser feitas traduções para o projeto?
2. Devemos embasar a tradução nos arquivos deste repositorio? ou no manual oficial (inglês)?
3. Como é a sincronização com o manual oficial?

**Comment by DyeffersonAz** [comment]
Olá, bem-vindo!
O fluxo de trabalho até o momento tem sido por meio da criação de _**draft** pull requests_ ou _issues_ que vão ter seu _merge_ quando o administrador do projeto, o @mizerablebr revisar o texto.
Sobre o embasamento, sempre é bom manter a consistência com os termos já utilizados tanto nas traduções daqui do manual quanto nas traduções da própria interface do Anki.
Infelizmente não sei como é a sincronização com o manual oficial, mas esse é o repositório oficial para a língua portuguesa, portanto, não se preocupe com suas mudanças serem ou não publicadas (caso estejam corretas, é claro).

Agradeço pela vontade de contribuir.

**Comment by mizerablebr** [comment]
O @DyeffersonAz explicou bem, seja bem vindo e conte conosco!

**Comment by paulolimac** [comment]
Grato pela informações.
